# Generated by Django 3.0.6 on 2020-06-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0002_auto_20200531_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopcached',
            name='workshop_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshopcached',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
